batch_size: 1
data_locations:
  json_file: ../train.json
  photos_ids: ../data/nyc/photos/processed/pano_ids.txt
  photos_matrix: ../data/nyc/photos/processed/ResNet
  photos_links: ../data/nyc/photos/streetview/manhattan_metadata_links.tsv
epochs: 20
gpus: 0
lr: 0.08
name: dbr_setup
