batch_size: 8
data_locations:
  json_file: ../practice.json
  photos_ids: ../data/nyc/photos/processed/pano_ids.txt
  photos_matrix: ../dbr/data/nyc/photos/processed/ResNet
epochs: 20
lr: 0.08
name: dbr_setup
